const dataSources = [
  {
    id: 0,
    datasource_name: "EBSI",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 1,
    datasource_name: "EBSG",
    description: "R12 2 Test environment",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 2,
    datasource_name: "EBST",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 3,
    datasource_name: "EBSO",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 4,
    datasource_name: "EBSX",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 5,
    datasource_name: "EBSS",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "ERRORED",
    default_datasource: "false",
  },
  {
    id: 6,
    datasource_name: "EBSO",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 7,
    datasource_name: "EBSD",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "COMPLETED",
    default_datasource: "false",
  },
  {
    id: 8,
    datasource_name: "EBSB",
    description: "This is the first source",
    application_type: "EBS",
    application_type_version: "R12",
    last_access_synchronization_date: "07/26/2021 13.14.21",
    last_access_synchronization_status: "COMPLETED",
    last_transaction_synchronization_date: "07/26/2021 13.14.21",
    last_transaction_synchronization_status: "NOT_STARTED",
    default_datasource: "false",
  },
];
export default dataSources;
// Datasource Name , Description, Application Type, Application Type Version, Last Access Synchronization Date, Last Access Synchronization Status, Last Transaction Synchronization Date, Last Transaction Synchronization Status, Default Datasource
